# Lightning Activity Analysis - Exploratory Data Analysis

This notebook explores lightning activity data from WWLLN over a 10-year period within a 25° x 25° region.

## Objectives:
- Analyze temporal patterns of lightning occurrence
- Explore spatial distribution of lightning events
- Identify potential trends and anomalies

## 1. Imports

In [ ]:
from scipy.io import loadmat
import os
import pandas as pd

C:\Users\cari_\miniconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\cari_\miniconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\cari_\miniconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


## 2. Data Loading

In [7]:
base_path = os.getcwd()
input_path = os.path.join(base_path,'Data','raw','Rayos_Ushuaia')

In [8]:
all_files=os.listdir(input_path)
all_files

['caja_EA9_2009.mat',
 'caja_EA9_2010.mat',
 'caja_EA9_2011.mat',
 'caja_EA9_2012.mat',
 'caja_EA9_2013.mat',
 'caja_EA9_2014.mat',
 'caja_EA9_2015.mat',
 'caja_EA9_2016.mat',
 'caja_EA9_2017.mat',
 'caja_EA9_2018.mat',
 'caja_EA9_2019.mat',
 'caja_EA9_2020.mat',
 'caja_EA_suma9_2009.mat',
 'caja_EA_suma9_2010.mat',
 'caja_EA_suma9_2011.mat',
 'caja_EA_suma9_2012.mat',
 'caja_EA_suma9_2013.mat',
 'caja_EA_suma9_2014.mat',
 'caja_EA_suma9_2015.mat',
 'caja_EA_suma9_2016.mat',
 'caja_EA_suma9_2017.mat',
 'caja_EA_suma9_2018.mat',
 'caja_EA_suma9_2019.mat',
 'caja_EA_suma9_2020.mat']

### 2.1 File Structure Inspection

I inspect a sample of each file type to identify relevant variables.

In [35]:
D2009=loadmat(os.path.join(input_path,'caja_EA9_2009'))

keys = [k for k in D2009.keys() if not k.startswith("__")]

for k in keys:
    print(f'\n=== Variable: {k} ===')
    print('Type: ', type(D2009[k]))
    print('Shape: ', D2009[k].shape)
    print('Sample: \n', D2009[k][:3]) 


=== Variable: datos1_w ===
Type:  <class 'numpy.ndarray'>
Shape:  (1353, 13)
Sample: 
 [[ 2.00900000e+03  4.00000000e+00  1.60000000e+01  2.30000000e+01
   2.10000000e+01  5.36105400e+00 -5.22525000e+01 -7.45656000e+01
   8.40000000e+00  5.00000000e+00  2.78751774e+04  1.83340766e+04
   5.00000000e+00]
 [ 2.00900000e+03  4.00000000e+00  1.70000000e+01  0.00000000e+00
   4.60000000e+01  1.41304580e+01 -6.47794000e+01 -5.95186000e+01
   2.96000000e+01  6.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 2.00900000e+03  4.00000000e+00  1.70000000e+01  0.00000000e+00
   5.90000000e+01  5.33057530e+01 -5.18052000e+01 -7.35489000e+01
   1.56000000e+01  6.00000000e+00  2.81604890e+03  1.03880980e+03
   4.00000000e+00]]


In [36]:
D2009S=loadmat(os.path.join(input_path,'caja_EA_suma9_2009'))

keys = [k for k in D2009S.keys() if not k.startswith("__")]

for k in keys:
    print(f'\n=== Variable: {k} ===')
    print('Type: ',type(D2009S[k]))
    print('Shape: ', D2009S[k].shape)
    print('Sample: \n', D2009S[k][:3]) 



=== Variable: rayos_dias_w ===
Type:  <class 'numpy.ndarray'>
Shape:  (261, 4)
Sample: 
 [[2009    4   15    0]
 [2009    4   16    1]
 [2009    4   17    2]]


I verify all files have a single non-metadata variable.

In [37]:
for file in all_files:
    data = loadmat(os.path.join(input_path, file))
    keys = [k for k in data.keys() if not k.startswith("__")]
    
    if len(keys) != 1:
        print(f"{file} has multiple variables: {keys}")

### 2.2 Dataset Separation and File Conversion

I build a function that loads .mat files, converts them into pandas DataFrames and saves them as .csv files for easier data analysis.

In [ ]:
def process_mat_file(file, input_path, output_path):
    
    full_path = os.path.join(input_path, file)
    
    data = loadmat(full_path)
    
    key = [k for k in data.keys() if not k.startswith("__")][0]
    array = data[key]
    
    df = pd.DataFrame(array)
    
    name = os.path.splitext(file)[0]
    
    df.to_csv(os.path.join(output_path, f"{name}.csv"), index=False)

I separate the dataset into two categories: 

- Events: individual lightning strike records
- Daily: total number of lightning strikes per day

In [ ]:
files = [f for f in all_files if "suma" not in f]
Sfiles = [f for f in all_files if "suma" in f]

print('files: ', files)
print('Sfiles: ', Sfiles)

output_path = os.path.join(base_path,'Data','raw',"Events_csv")
os.makedirs(output_path, exist_ok=True)

Soutput_path = os.path.join(base_path,'Data','raw', "Daily_csv")
os.makedirs(Soutput_path, exist_ok=True)


In [ ]:
for file in files:
    process_mat_file(file, input_path, output_path)

for file in Sfiles:
    process_mat_file(file, input_path, Soutput_path)